### PR TITLE
Point to staging

### LINKED ISSUE #32: Pointing app to staging
I ran across an issue on this ticket. React-native's WebView supports passing headers, but they are not being reused on subsequent requests, which makes the first page to load but then you can't go anywhere. Here it is the RN issue: https://github.com/facebook/react-native/issues/8693

There is a workaround to make the WebView behave as a controlled element, and force a reload each time the url changes. In our case, we would lose the client-side redirection behaviour. We either try this option, or we will need to find another way of handling our staging env for the app 😞 

@tpreusse @patte thoughts?

### PR DESCRIPTION
**Pull request by diegomura**
Fixes #32

### CODE REVIEW

**Comment by tpreusse** [comment]
You don't have to navigate the web view to the unlock path. You should just be able to set it with cookie manger:
```js
CookieManager.setFromResponse('example.com', `OpenSesame=${encodeURIComponent(CURTAIN_BACKDOOR_URL)}; Path=/; Expires=Thu, 01 Jan 2030 00:00:00 GMT; HttpOnly`)
```

**Comment by diegomura** [comment]
Thanks @tpreusse ! 

On Friday I had an issue with `react-native-cookies` (the native lib we are using as cookie manager) in which I wasn't able to get the cookies from the `CURTAIN_BACKDOOR_URL`.
At first I came to the conclusion that somehow that lib and `react-native-wkwebview-reborn` (an iOS webview implementation that supports the swipe back gesture) were conflicting, but does not make much sense to me yet. That's why here I was trying the navigation solution.

I'll try that particular method and update here

**Comment by diegomura** [comment]
`setFromResponse` worked great! Thanks for that. Ready for merge now!

**Comment by diegomura** [comment]
I'm merging this so I can have these changes to test Universal Links

**Pull request merged**
